// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BatchSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408173514_DeleteOrderBatchStep")]
    partial class DeleteOrderBatchStep
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Alarms.AlarmDefinition", b =>
                {
                    b.Property<string>("AlarmDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("AlarmClass")
                        .HasColumnType("int");

                    b.Property<string>("AlarmText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AlarmDefinitionId");

                    b.HasIndex("StationId");

                    b.ToTable("AlarmDefinitions");
                });

            modelBuilder.Entity("Domain.Alarms.AlarmEvent", b =>
                {
                    b.Property<Guid>("AlarmEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("AckAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AckBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmDefinitionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAcked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductionOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AlarmEventId");

                    b.HasIndex("AlarmDefinitionId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("StationId");

                    b.HasIndex("OrderBatchId", "OccurredAt");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("Domain.Lines.Line", b =>
                {
                    b.Property<string>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LineId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("Domain.Lines.LineCurrentStatus", b =>
                {
                    b.Property<string>("LineCurrentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LineCurrentStatusId");

                    b.HasIndex("LineId")
                        .IsUnique();

                    b.ToTable("LineCurrentStatuses");
                });

            modelBuilder.Entity("Domain.Lines.LineStatusHistory", b =>
                {
                    b.Property<Guid>("LineStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("LineStatusHistoryId");

                    b.HasIndex("LineId");

                    b.ToTable("LineStatusHistories");
                });

            modelBuilder.Entity("Domain.Logins.Login", b =>
                {
                    b.Property<string>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Domain.Materials.Material", b =>
                {
                    b.Property<string>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Domain.OrderBatchs.BatchWeightResults.BatchWeighingResult", b =>
                {
                    b.Property<Guid>("BatchWeighingResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("ActualKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DeviationKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsWithinTolerance")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("OrderBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TargetKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ToleranceMaxKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ToleranceMinKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("BatchWeighingResultId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderBatchId", "CapturedAt");

                    b.ToTable("BatchWeighingResults");
                });

            modelBuilder.Entity("Domain.OrderBatchs.OrderBatch", b =>
                {
                    b.Property<Guid>("OrderBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("BatchNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<string>("LineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ProductionOrderDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OrderBatchId");

                    b.HasIndex("CurrentStationId");

                    b.HasIndex("LineId");

                    b.HasIndex("ProductionOrderDetailId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("OrderBatchs");
                });

            modelBuilder.Entity("Domain.ProductionOrders.ProductionOrder", b =>
                {
                    b.Property<Guid>("ProductionOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlannedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProductionOrderId");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("Domain.ProductionOrders.ProductionOrderDetail", b =>
                {
                    b.Property<Guid>("ProductionOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("BatchQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipeSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("ProductionOrderDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("RecipeId");

                    b.ToTable("ProductionOrderDetails");
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Recipes.Recipe", b =>
                {
                    b.Property<string>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Domain.Recipes.RecipeMaterial", b =>
                {
                    b.Property<string>("RecipeMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TargetKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ToleranceMaxKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ToleranceMinKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("RecipeMaterialId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeMaterials");
                });

            modelBuilder.Entity("Domain.Stations.Station", b =>
                {
                    b.Property<string>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StationId");

                    b.HasIndex("LineId");

                    b.HasIndex("StationTypeId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Domain.Stations.StationCurrentStatus", b =>
                {
                    b.Property<string>("StationCurrentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CurrentBatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrentBatchOrderBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrentOrderProductionOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StationCurrentStatusId");

                    b.HasIndex("CurrentBatchOrderBatchId");

                    b.HasIndex("CurrentOrderProductionOrderId");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("StationCurrentStatuses");
                });

            modelBuilder.Entity("Domain.Stations.StationType", b =>
                {
                    b.Property<string>("StationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("StationTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationTypeId");

                    b.ToTable("StationTypes");
                });

            modelBuilder.Entity("Domain.Alarms.AlarmDefinition", b =>
                {
                    b.HasOne("Domain.Stations.Station", "Station")
                        .WithMany("AlarmDefinitions")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Domain.Alarms.AlarmEvent", b =>
                {
                    b.HasOne("Domain.Alarms.AlarmDefinition", "AlarmDefinition")
                        .WithMany()
                        .HasForeignKey("AlarmDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.OrderBatchs.OrderBatch", "OrderBatch")
                        .WithMany()
                        .HasForeignKey("OrderBatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.ProductionOrders.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Stations.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmDefinition");

                    b.Navigation("OrderBatch");

                    b.Navigation("ProductionOrder");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Domain.Lines.LineCurrentStatus", b =>
                {
                    b.HasOne("Domain.Lines.Line", "Line")
                        .WithOne("CurrentStatus")
                        .HasForeignKey("Domain.Lines.LineCurrentStatus", "LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Domain.Lines.LineStatusHistory", b =>
                {
                    b.HasOne("Domain.Lines.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Domain.OrderBatchs.BatchWeightResults.BatchWeighingResult", b =>
                {
                    b.HasOne("Domain.Materials.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.OrderBatchs.OrderBatch", "OrderBatch")
                        .WithMany("BatchWeighingResults")
                        .HasForeignKey("OrderBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("OrderBatch");
                });

            modelBuilder.Entity("Domain.OrderBatchs.OrderBatch", b =>
                {
                    b.HasOne("Domain.Stations.Station", "CurrentStation")
                        .WithMany()
                        .HasForeignKey("CurrentStationId");

                    b.HasOne("Domain.Lines.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId");

                    b.HasOne("Domain.ProductionOrders.ProductionOrderDetail", "ProductionOrderDetail")
                        .WithMany("OrderBatches")
                        .HasForeignKey("ProductionOrderDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.ProductionOrders.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentStation");

                    b.Navigation("Line");

                    b.Navigation("ProductionOrder");

                    b.Navigation("ProductionOrderDetail");
                });

            modelBuilder.Entity("Domain.ProductionOrders.ProductionOrderDetail", b =>
                {
                    b.HasOne("Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ProductionOrders.ProductionOrder", "ProductionOrder")
                        .WithMany("ProductionOrderDetails")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.HasOne("Domain.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Recipes.RecipeMaterial", b =>
                {
                    b.HasOne("Domain.Materials.Material", "Material")
                        .WithMany("RecipeMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeMaterials")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Stations.Station", b =>
                {
                    b.HasOne("Domain.Lines.Line", "Line")
                        .WithMany("Stations")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Stations.StationType", "StationType")
                        .WithMany("Stations")
                        .HasForeignKey("StationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("StationType");
                });

            modelBuilder.Entity("Domain.Stations.StationCurrentStatus", b =>
                {
                    b.HasOne("Domain.OrderBatchs.OrderBatch", "CurrentBatch")
                        .WithMany()
                        .HasForeignKey("CurrentBatchOrderBatchId");

                    b.HasOne("Domain.ProductionOrders.ProductionOrder", "CurrentOrder")
                        .WithMany()
                        .HasForeignKey("CurrentOrderProductionOrderId");

                    b.HasOne("Domain.Stations.Station", "Station")
                        .WithOne("CurrentStatus")
                        .HasForeignKey("Domain.Stations.StationCurrentStatus", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentBatch");

                    b.Navigation("CurrentOrder");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Domain.Lines.Line", b =>
                {
                    b.Navigation("CurrentStatus");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("Domain.Materials.Material", b =>
                {
                    b.Navigation("RecipeMaterials");
                });

            modelBuilder.Entity("Domain.OrderBatchs.OrderBatch", b =>
                {
                    b.Navigation("BatchWeighingResults");
                });

            modelBuilder.Entity("Domain.ProductionOrders.ProductionOrder", b =>
                {
                    b.Navigation("ProductionOrderDetails");
                });

            modelBuilder.Entity("Domain.ProductionOrders.ProductionOrderDetail", b =>
                {
                    b.Navigation("OrderBatches");
                });

            modelBuilder.Entity("Domain.Recipes.Recipe", b =>
                {
                    b.Navigation("RecipeMaterials");
                });

            modelBuilder.Entity("Domain.Stations.Station", b =>
                {
                    b.Navigation("AlarmDefinitions");

                    b.Navigation("CurrentStatus");
                });

            modelBuilder.Entity("Domain.Stations.StationType", b =>
                {
                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
